// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Start_screen_init(void)
{
ui_Start = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Start, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image3 = lv_img_create(ui_Start);
lv_img_set_src(ui_Image3, &ui_img_577703776);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 300
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 278
lv_obj_set_x( ui_Image3, 1 );
lv_obj_set_y( ui_Image3, -9 );
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image3,275);

lv_obj_add_event_cb(ui_Start, ui_event_Start, LV_EVENT_ALL, NULL);

}
