// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Home_screen_init(void)
{
ui_Home = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Home, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TabView1 = lv_tabview_create(ui_Home, LV_DIR_TOP, 50);
lv_obj_set_width( ui_TabView1, 320);
lv_obj_set_height( ui_TabView1, 240);
lv_obj_set_align( ui_TabView1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabView1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_TabView1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TabView1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_TabView1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );

lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0xFFFFFF),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabView1), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0x000000),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView1), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0xFFFFFF),  LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Dashboard = lv_tabview_add_tab(ui_TabView1, "Dashboard");

ui_PanelTemperature = lv_obj_create(ui_Dashboard);
lv_obj_set_width( ui_PanelTemperature, 292);
lv_obj_set_height( ui_PanelTemperature, 37);
lv_obj_set_x( ui_PanelTemperature, -1 );
lv_obj_set_y( ui_PanelTemperature, -71 );
lv_obj_set_align( ui_PanelTemperature, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelTemperature, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BarTemperature = lv_bar_create(ui_PanelTemperature);
lv_bar_set_value(ui_BarTemperature,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_BarTemperature, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_BarTemperature, 150);
lv_obj_set_height( ui_BarTemperature, 13);
lv_obj_set_x( ui_BarTemperature, -53 );
lv_obj_set_y( ui_BarTemperature, 0 );
lv_obj_set_align( ui_BarTemperature, LV_ALIGN_CENTER );

ui_LabelTemperature = lv_label_create(ui_PanelTemperature);
lv_obj_set_width( ui_LabelTemperature, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTemperature, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelTemperature, 84 );
lv_obj_set_y( ui_LabelTemperature, 0 );
lv_obj_set_align( ui_LabelTemperature, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelTemperature,"Temperature");

ui_PanelHumidity = lv_obj_create(ui_Dashboard);
lv_obj_set_width( ui_PanelHumidity, 292);
lv_obj_set_height( ui_PanelHumidity, 37);
lv_obj_set_x( ui_PanelHumidity, -1 );
lv_obj_set_y( ui_PanelHumidity, -25 );
lv_obj_set_align( ui_PanelHumidity, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelHumidity, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BarHumidity = lv_bar_create(ui_PanelHumidity);
lv_bar_set_value(ui_BarHumidity,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_BarHumidity, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_BarHumidity, 150);
lv_obj_set_height( ui_BarHumidity, 13);
lv_obj_set_x( ui_BarHumidity, -53 );
lv_obj_set_y( ui_BarHumidity, 0 );
lv_obj_set_align( ui_BarHumidity, LV_ALIGN_CENTER );

ui_LabelHumidity = lv_label_create(ui_PanelHumidity);
lv_obj_set_width( ui_LabelHumidity, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHumidity, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelHumidity, 84 );
lv_obj_set_y( ui_LabelHumidity, 0 );
lv_obj_set_align( ui_LabelHumidity, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelHumidity,"Humidity");

ui_PanelSoilMoisture = lv_obj_create(ui_Dashboard);
lv_obj_set_width( ui_PanelSoilMoisture, 292);
lv_obj_set_height( ui_PanelSoilMoisture, 37);
lv_obj_set_x( ui_PanelSoilMoisture, -1 );
lv_obj_set_y( ui_PanelSoilMoisture, 19 );
lv_obj_set_align( ui_PanelSoilMoisture, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelSoilMoisture, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BarSoilMoisture = lv_bar_create(ui_PanelSoilMoisture);
lv_bar_set_value(ui_BarSoilMoisture,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_BarSoilMoisture, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_BarSoilMoisture, 150);
lv_obj_set_height( ui_BarSoilMoisture, 13);
lv_obj_set_x( ui_BarSoilMoisture, -53 );
lv_obj_set_y( ui_BarSoilMoisture, 0 );
lv_obj_set_align( ui_BarSoilMoisture, LV_ALIGN_CENTER );

ui_LabelSoilMoisture = lv_label_create(ui_PanelSoilMoisture);
lv_obj_set_width( ui_LabelSoilMoisture, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSoilMoisture, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelSoilMoisture, 84 );
lv_obj_set_y( ui_LabelSoilMoisture, 0 );
lv_obj_set_align( ui_LabelSoilMoisture, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSoilMoisture,"Soil Moisture");

ui_PanelLux = lv_obj_create(ui_Dashboard);
lv_obj_set_width( ui_PanelLux, 292);
lv_obj_set_height( ui_PanelLux, 37);
lv_obj_set_x( ui_PanelLux, -1 );
lv_obj_set_y( ui_PanelLux, 63 );
lv_obj_set_align( ui_PanelLux, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelLux, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BarLux = lv_bar_create(ui_PanelLux);
lv_bar_set_value(ui_BarLux,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_BarLux, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_BarLux, 150);
lv_obj_set_height( ui_BarLux, 13);
lv_obj_set_x( ui_BarLux, -53 );
lv_obj_set_y( ui_BarLux, 0 );
lv_obj_set_align( ui_BarLux, LV_ALIGN_CENTER );

ui_LabelLux = lv_label_create(ui_PanelLux);
lv_obj_set_width( ui_LabelLux, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelLux, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelLux, 84 );
lv_obj_set_y( ui_LabelLux, 0 );
lv_obj_set_align( ui_LabelLux, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelLux,"Lux");

ui_Action = lv_tabview_add_tab(ui_TabView1, "Action");

ui_Panel6 = lv_obj_create(ui_Action);
lv_obj_set_width( ui_Panel6, 146);
lv_obj_set_height( ui_Panel6, 81);
lv_obj_set_x( ui_Panel6, -77 );
lv_obj_set_y( ui_Panel6, -51 );
lv_obj_set_align( ui_Panel6, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Switch1 = lv_switch_create(ui_Panel6);
lv_obj_set_width( ui_Switch1, 84);
lv_obj_set_height( ui_Switch1, 33);
lv_obj_set_x( ui_Switch1, 0 );
lv_obj_set_y( ui_Switch1, 10 );
lv_obj_set_align( ui_Switch1, LV_ALIGN_CENTER );


ui_Label6 = lv_label_create(ui_Panel6);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, -2 );
lv_obj_set_y( ui_Label6, -22 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"Switch 1");

ui_Panel7 = lv_obj_create(ui_Action);
lv_obj_set_width( ui_Panel7, 146);
lv_obj_set_height( ui_Panel7, 81);
lv_obj_set_x( ui_Panel7, 73 );
lv_obj_set_y( ui_Panel7, -51 );
lv_obj_set_align( ui_Panel7, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Switch2 = lv_switch_create(ui_Panel7);
lv_obj_set_width( ui_Switch2, 84);
lv_obj_set_height( ui_Switch2, 33);
lv_obj_set_x( ui_Switch2, 0 );
lv_obj_set_y( ui_Switch2, 10 );
lv_obj_set_align( ui_Switch2, LV_ALIGN_CENTER );


ui_Label1 = lv_label_create(ui_Panel7);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -2 );
lv_obj_set_y( ui_Label1, -22 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Switch 2");

ui_Panel8 = lv_obj_create(ui_Action);
lv_obj_set_width( ui_Panel8, 146);
lv_obj_set_height( ui_Panel8, 81);
lv_obj_set_x( ui_Panel8, -77 );
lv_obj_set_y( ui_Panel8, 36 );
lv_obj_set_align( ui_Panel8, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Switch3 = lv_switch_create(ui_Panel8);
lv_obj_set_width( ui_Switch3, 84);
lv_obj_set_height( ui_Switch3, 33);
lv_obj_set_x( ui_Switch3, 0 );
lv_obj_set_y( ui_Switch3, 10 );
lv_obj_set_align( ui_Switch3, LV_ALIGN_CENTER );


ui_Label7 = lv_label_create(ui_Panel8);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, -2 );
lv_obj_set_y( ui_Label7, -22 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"Switch 3");

ui_Panel9 = lv_obj_create(ui_Action);
lv_obj_set_width( ui_Panel9, 146);
lv_obj_set_height( ui_Panel9, 81);
lv_obj_set_x( ui_Panel9, 74 );
lv_obj_set_y( ui_Panel9, 36 );
lv_obj_set_align( ui_Panel9, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Switch4 = lv_switch_create(ui_Panel9);
lv_obj_set_width( ui_Switch4, 84);
lv_obj_set_height( ui_Switch4, 33);
lv_obj_set_x( ui_Switch4, 0 );
lv_obj_set_y( ui_Switch4, 10 );
lv_obj_set_align( ui_Switch4, LV_ALIGN_CENTER );


ui_Label8 = lv_label_create(ui_Panel9);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, -2 );
lv_obj_set_y( ui_Label8, -22 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"Switch 4");

ui_Log = lv_tabview_add_tab(ui_TabView1, "Log");

ui_PanelLog = lv_obj_create(ui_Log);
lv_obj_set_width( ui_PanelLog, 283);
lv_obj_set_height( ui_PanelLog, 156);
lv_obj_set_x( ui_PanelLog, 1 );
lv_obj_set_y( ui_PanelLog, -5 );
lv_obj_set_align( ui_PanelLog, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelLog, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelLog = lv_label_create(ui_PanelLog);
lv_obj_set_width( ui_LabelLog, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelLog, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelLog, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelLog,"LogText");

}
