// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Start
void ui_Start_screen_init(void);
void ui_event_Start(lv_event_t *e);
lv_obj_t *ui_Start;
lv_obj_t *ui_Image3;

// SCREEN: ui_Home
void ui_Home_screen_init(void);
lv_obj_t *ui_Home;
lv_obj_t *ui_TabView1;
lv_obj_t *ui_Dashboard;
lv_obj_t *ui_PanelTemperature;
lv_obj_t *ui_BarTemperature;
lv_obj_t *ui_LabelTemperature;
lv_obj_t *ui_PanelHumidity;
lv_obj_t *ui_BarHumidity;
lv_obj_t *ui_LabelHumidity;
lv_obj_t *ui_PanelSoilMoisture;
lv_obj_t *ui_BarSoilMoisture;
lv_obj_t *ui_LabelSoilMoisture;
lv_obj_t *ui_PanelLux;
lv_obj_t *ui_BarLux;
lv_obj_t *ui_LabelLux;
lv_obj_t *ui_Action;
lv_obj_t *ui_Panel6;
lv_obj_t *ui_Switch1;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Panel7;
lv_obj_t *ui_Switch2;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Panel8;
lv_obj_t *ui_Switch3;
lv_obj_t *ui_Label7;
lv_obj_t *ui_Panel9;
lv_obj_t *ui_Switch4;
lv_obj_t *ui_Label8;
lv_obj_t *ui_Log;
lv_obj_t *ui_PanelLog;
lv_obj_t *ui_LabelLog;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_614662921[1] = {&ui_img_577703776};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Start(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_SCREEN_LOADED)
    {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 1000, 2000, &ui_Home_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Start_screen_init();
    ui_Home_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Start);
}
