// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Start
void ui_Start_screen_init(void);
void ui_event_Start( lv_event_t * e);
extern lv_obj_t *ui_Start;
extern lv_obj_t *ui_Image3;
// SCREEN: ui_Home
void ui_Home_screen_init(void);
extern lv_obj_t *ui_Home;
extern lv_obj_t *ui_TabView1;
extern lv_obj_t *ui_Dashboard;
extern lv_obj_t *ui_PanelTemperature;
extern lv_obj_t *ui_BarTemperature;
extern lv_obj_t *ui_LabelTemperature;
extern lv_obj_t *ui_PanelHumidity;
extern lv_obj_t *ui_BarHumidity;
extern lv_obj_t *ui_LabelHumidity;
extern lv_obj_t *ui_PanelSoilMoisture;
extern lv_obj_t *ui_BarSoilMoisture;
extern lv_obj_t *ui_LabelSoilMoisture;
extern lv_obj_t *ui_PanelLux;
extern lv_obj_t *ui_BarLux;
extern lv_obj_t *ui_LabelLux;
extern lv_obj_t *ui_Action;
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_Switch1;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui_Switch2;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Panel8;
extern lv_obj_t *ui_Switch3;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Panel9;
extern lv_obj_t *ui_Switch4;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Log;
extern lv_obj_t *ui_PanelLog;
extern lv_obj_t *ui_LabelLog;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_577703776);   // assets/Bildschirmfoto 2023-12-13 um 20.28.04.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
